services:
  todo_list_db:
    image: postgres:latest
    container_name: todo_list_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"
    networks:
      - todo_list_network

  todo_list_pgadmin:
    image: dpage/pgadmin4
    container_name: todo_list_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - todo_list_db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - todo_list_network

volumes:
  pgadmin_data:

networks:
  todo_list_network:
    external: true